/* ── CMDBLOCK REDESIGN — Lesson data ─────────────────────── */
window.LESSONS = {
  'bedrock-iron': {
    title: 'The Basics — Bedrock',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Iron Course' }],
    tier: 'IRON · BASICS',
    color: 'var(--iron)',
    progressKey: 'bedrock-iron',
    lessons: [
      { name: 'WHAT ARE COMMANDS?', summary: 'The anatomy of a slash command and what they can do in your world.' },
      { name: 'ENABLING COMMANDS', summary: 'Turning on cheats, creating a practice world, and opening the chat.' },
      { name: 'CHAT VS COMMAND BLOCKS', summary: 'The three types of command blocks and when to use each.' },
      { name: '/gamemode', summary: 'Switch between survival, creative, adventure, and spectator.' },
      { name: '/tp & /spawnpoint', summary: 'Teleport players, entities, and reset their spawn.' },
      { name: '/give & /clear', summary: 'Hand items to players. Clean their inventory just as easily.' },
      { name: '/time & /weather', summary: 'Skip to night. Stop the rain. Lock the cycle for cinematics.' },
      { name: 'TARGET SELECTORS', summary: 'The five selectors and the arguments that filter them.' },
      { name: 'COORDINATE SYSTEMS', summary: 'Absolute, relative (~), and local (^) — when to use each.' },
      { name: '/say, /tell & /msg', summary: 'Broadcast, whisper, or DM. The basics of chat output.' },
      { name: '/difficulty & /gamerule', summary: 'Server-wide rules that change how your world plays.' },
      { name: '/kill & /effect', summary: 'Despawn entities. Apply potion effects with precision.' },
      { name: '/xp & /enchant', summary: 'Hand out experience and apply enchantments by command.' },
      { name: 'IRON REVIEW', summary: 'What you now know. Practice challenges. Next steps.' },
    ],
  },
  'bedrock-emerald': {
    title: 'Intermediate Course — Bedrock',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Emerald Course' }],
    tier: 'EMERALD · INTERMEDIATE',
    color: 'var(--emerald)',
    progressKey: 'bedrock-emerald',
    lessons: [
      { name: '/fill BASICS', summary: 'Replace, hollow, outline, keep. Fill modes that change the world fast.' },
      { name: '/clone DEEP DIVE', summary: 'Copy regions. Mask. Replace. Move structures around the map.' },
      { name: '/setblock & /structure', summary: 'Place single blocks. Save and load structure files.' },
      { name: '/effect ADVANCED', summary: 'Every Bedrock effect and the practical combos.' },
      { name: '/summon & /event', summary: 'Spawn entities. Fire events to mutate them on spawn.' },
      { name: 'COMMAND BLOCK TYPES', summary: 'Impulse, Chain, Repeat. Conditional vs unconditional.' },
      { name: 'COMMAND BLOCK CHAINS', summary: 'Build a welcome system that fires on join in one tick.' },
      { name: '/execute BASICS', summary: 'Run a command as another entity. The if-block condition.' },
      { name: '/execute ADVANCED', summary: 'Chain sub-commands. Filter by entity, position, score.' },
      { name: '/scoreboard OBJECTIVES', summary: 'Create, set, and read objectives. The basic counter.' },
      { name: 'SCOREBOARD OPERATIONS', summary: 'Add, subtract, multiply, copy between objectives.' },
      { name: '/tag SYSTEM', summary: 'Yes/no flags on any entity. Cheaper than scoreboards.' },
      { name: '/replaceitem', summary: 'Replace items in any slot of any player or entity.' },
      { name: 'TICK-BASED LOOPS', summary: 'The game tick. Timer patterns that run forever.' },
      { name: '/tickingarea', summary: 'Keep chunks loaded for systems away from players.' },
      { name: 'WHY IT MATTERS', summary: 'Pull it together: from commands to working systems.' },
      { name: '/function FILES', summary: 'Bundle many commands into a single callable file.' },
      { name: '/damage & /ride', summary: 'Deal damage by type. Force entities to mount each other.' },
      { name: '/inputpermission & /hud', summary: 'Restrict player inputs. Toggle HUD elements.' },
      { name: 'EMERALD REVIEW', summary: 'What you can now build. Next: the Diamond course.' },
    ],
  },
  'bedrock-diamond': {
    title: 'Expert Course — Bedrock',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Diamond Course' }],
    tier: 'DIAMOND · EXPERT',
    color: 'var(--diamond)',
    progressKey: 'bedrock-diamond',
    lessons: [
      { name: '/title & /subtitle', summary: 'Cinematic on-screen text. Fade, stay, fade out.' },
      { name: '/titleraw & JSON TEXT', summary: 'Styled titles with JSON. Colors, hover, click.' },
      { name: '/tellraw', summary: 'Styled chat with click and hover events.' },
      { name: '/playsound & /stopsound', summary: 'Trigger any sound at any location with falloff.' },
      { name: '/music', summary: 'Background music control. Crossfade between tracks.' },
      { name: '/camera SYSTEM', summary: 'Camera positions, presets, smooth transitions.' },
      { name: '/particle EFFECTS', summary: 'Visual particles. Common particle catalog.' },
      { name: '/fog & ATMOSPHERE', summary: 'Fog distance, density, color per biome or area.' },
      { name: '/dialogue & NPCs', summary: 'Interactive NPC dialogue trees with branches.' },
      { name: 'BEHAVIOR PACKS BASICS', summary: 'Custom entities, items, rules. Pack structure.' },
      { name: 'OPTIMIZATION & DEBUGGING', summary: 'Performance tips. Debugging techniques.' },
      { name: 'MARKETPLACE PREPARATION', summary: 'Submission checklist and testing protocol.' },
      { name: 'DIAMOND GRADUATION', summary: 'The complete journey. Projects you can build.' },
    ],
  },
  'java-iron': {
    title: 'The Basics — Java',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Iron (Java)' }],
    tier: 'IRON · JAVA · BASICS',
    color: 'var(--iron)',
    progressKey: 'java-iron',
    lessons: [
      { name: 'WHAT ARE COMMANDS?', summary: 'How Java handles slash commands. Permission levels and op.' },
      { name: 'COORDINATES (X, Y, Z)', summary: 'The Java coord system. Block coords vs entity coords.' },
      { name: 'RELATIVE COORDINATES (~)', summary: 'Coords relative to the executor\'s position.' },
      { name: 'LOCAL COORDINATES (^)', summary: 'Coords relative to where the executor is facing.' },
      { name: 'TARGET SELECTORS', summary: 'Java selectors and arg syntax. Differences from Bedrock.' },
      { name: 'TIME & WEATHER', summary: '/time set, /weather, daylight cycle gamerules.' },
      { name: 'SPAWN & RESPAWN', summary: '/setworldspawn, /spawnpoint, /forceload (Java only).' },
      { name: 'GAMERULES', summary: 'Java-specific gamerules: doMobLoot, keepInventory, sendCommandFeedback.' },
      { name: 'GIVING ITEMS', summary: '/give with NBT. Modern item components (1.20.5+).' },
      { name: 'EFFECTS', summary: '/effect give and /effect clear. Hidden, ambient, infinite.' },
      { name: 'BASIC BUILDING', summary: '/setblock, /fill, /clone. The Java syntax.' },
      { name: 'FINAL PROJECT', summary: 'Build a 5-command test-world setup from scratch.' },
    ],
  },
  'java-emerald': {
    title: 'Intermediate Course — Java',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Emerald (Java)' }],
    tier: 'EMERALD · JAVA · INTERMEDIATE',
    color: 'var(--emerald)',
    progressKey: 'java-emerald',
    lessons: [
      { name: '/fill BASICS', summary: 'Replace mode, hollow, outline, destroy.' },
      { name: '/clone DEEP DIVE', summary: 'Cloning with masked, filtered, force, normal.' },
      { name: '/setblock & STRUCTURE BLOCKS', summary: 'Saving and loading .nbt structure files.' },
      { name: '/effect ADVANCED', summary: 'All Java effects. Hidden particles. Infinite duration.' },
      { name: '/summon & DATA TAGS', summary: 'NBT spawn data. Pre-tagged entities.' },
      { name: 'COMMAND BLOCK TYPES', summary: 'Impulse, Chain, Repeat. Always-active mode.' },
      { name: 'COMMAND BLOCK CHAINS', summary: 'Welcome system. Auto-triggered events.' },
      { name: '/execute BASICS', summary: 'as, at, run. The most powerful command in Java.' },
      { name: '/execute ADVANCED', summary: 'if, unless, store, anchored. Chaining everything.' },
      { name: '/scoreboard OBJECTIVES', summary: 'Criteria-based objectives. Trigger objectives.' },
      { name: 'SCOREBOARD OPERATIONS', summary: '+=, -=, *=, /=, %=, <, >, =, ><.' },
      { name: '/tag SYSTEM', summary: 'Yes/no flags. Cheaper than scoreboards for state.' },
      { name: '/loot SYSTEM', summary: 'Generate items from loot tables programmatically.' },
      { name: 'TICK-BASED LOOPS', summary: 'Repeating command blocks. Function tags. tick.json.' },
      { name: '/forceload', summary: 'Keep chunks loaded without a player nearby.' },
      { name: 'WHY IT MATTERS', summary: 'From commands to systems that run themselves.' },
      { name: '/function FILES', summary: 'Datapack functions. Pack structure. Reloading.' },
      { name: '/damage & /ride', summary: 'Custom damage types. Forced entity riding.' },
      { name: 'EMERALD REVIEW', summary: 'What you can now build. Next: Diamond course.' },
    ],
  },
  'java-diamond': {
    title: 'Expert Course — Java',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Diamond (Java)' }],
    tier: 'DIAMOND · JAVA · EXPERT',
    color: 'var(--diamond)',
    progressKey: 'java-diamond',
    lessons: [
      { name: '/title & /subtitle', summary: 'Cinematic on-screen text with fade timings.' },
      { name: 'JSON TEXT COMPONENTS', summary: 'Colors, click events, hover events, translatable text.' },
      { name: '/tellraw', summary: 'Styled chat. Embedded scores, selectors, NBT.' },
      { name: '/playsound & /stopsound', summary: 'All sound sources, mixing volumes, falloff.' },
      { name: 'PARTICLE EFFECTS', summary: 'Spawn particles. Force option. Particle commands per tick.' },
      { name: '/spawnpoint & /respawnanchor', summary: 'Override spawn behavior. World border interactions.' },
      { name: 'DATAPACK BASICS', summary: 'pack.mcmeta, functions, advancements, loot tables.' },
      { name: 'ADVANCEMENTS', summary: 'Custom triggers, rewards, hidden achievements.' },
      { name: 'CUSTOM RECIPES', summary: 'Shaped, shapeless, smelting, stonecutter, smithing.' },
      { name: 'PREDICATES', summary: 'Reusable conditions for loot tables and /execute.' },
      { name: 'ITEM MODIFIERS', summary: 'Modify items in place. Used by /item replace and /loot.' },
      { name: 'MARKETPLACE / RESOURCE PACKS', summary: 'Distribute datapacks alongside resource packs.' },
      { name: 'DIAMOND GRADUATION', summary: 'Projects you can build. Bonus: the Netherite track.' },
    ],
  },
  'java-netherite': {
    title: 'Netherite Course — Java',
    breadcrumb: [{ name: 'Learn', href: 'learn.html' }, { name: 'Netherite (Java)' }],
    tier: 'NETHERITE · BONUS',
    color: '#C8A287',
    progressKey: 'java-netherite',
    wip: true,
    lessons: [
      { name: 'READING THE F3 SCREEN', summary: 'Debug info. Targeted block. Light levels. Biome.' },
      { name: 'THE PIE CHART (SHIFT+F3)', summary: 'Tick performance breakdown. Find the lag source.' },
      { name: 'DIAGNOSING LAG', summary: 'Block entities, ticking entities, redstone loops.' },
      { name: 'BROKEN FARMS', summary: 'Common reasons a farm stops working. Spawn rules.' },
      { name: 'CHUNK BORDER (F3+G)', summary: 'See chunk boundaries. Mob caps. Spawn-chunk loading.' },
      { name: 'READ ANY WORLD LIKE CODE', summary: 'Use /forceload, /data get, and /execute as auditing tools.' },
      { name: 'PROFILING WITH SPARK', summary: 'Server-side profiler. CPU samplers. Memory.' },
      { name: 'NETHERITE GRADUATION', summary: 'You can now debug any Minecraft world.' },
    ],
  },
  'projects-easy': {
    title: 'Easy Projects',
    breadcrumb: [{ name: 'Projects', href: 'projects.html' }, { name: 'Easy' }],
    tier: 'PROJECTS · EASY',
    color: 'var(--cmd-green)',
    progressKey: 'projects-easy',
    lessons: [
      { name: 'COMMAND ELEVATOR', summary: 'A pressure plate teleporter between floors with cooldown.' },
      { name: 'CUSTOM DEATH MESSAGES', summary: 'Replace death announcements with themed lines.' },
      { name: 'WEATHER MACHINE', summary: 'Button-driven weather control station with effects.' },
      { name: 'TELEPORTER NETWORK', summary: 'Warp pads with particles, sounds, and detection.' },
    ],
  },
  'projects-medium': {
    title: 'Medium Projects',
    breadcrumb: [{ name: 'Projects', href: 'projects.html' }, { name: 'Medium' }],
    tier: 'PROJECTS · MEDIUM',
    color: 'var(--gold)',
    progressKey: 'projects-medium',
    lessons: [
      { name: 'TREASURE HUNT GAME', summary: 'Hidden treasures, hint tracker, completion reward chain.' },
      { name: 'SPEED BUILD CHALLENGE', summary: 'Timed comp with random theme + freeze on time-up.' },
      { name: 'HIDE & SEEK', summary: 'Multiplayer, seeker blindness, boundary enforcement.' },
      { name: 'WORKING TRAPS', summary: 'Arrow rain, floor collapse, poison gas — with auto-reset.' },
    ],
  },
  'projects-hard': {
    title: 'Hard Projects',
    breadcrumb: [{ name: 'Projects', href: 'projects.html' }, { name: 'Hard' }],
    tier: 'PROJECTS · HARD',
    color: 'var(--cmd-red)',
    progressKey: 'projects-hard',
    lessons: [
      { name: 'MOB WAVE SPAWNER', summary: 'Scaling waves. Boundary enforcement. Difficulty curves.' },
      { name: 'DAY/NIGHT EVENT SYSTEM', summary: 'Night raid + dawn bonus loop.' },
      { name: 'MINI GOLF COURSE', summary: 'Stroke counting, hole detection, par system.' },
      { name: 'ONE-BLOCK SKYBLOCK', summary: 'Block replacement with milestone phases.' },
      { name: 'PVP ARENA SETUP', summary: 'Scoreboards, teams, countdown system.' },
      { name: 'ARENA GAME LOOP', summary: 'Reset, repeat, broadcast winner.' },
      { name: 'CUSTOM BOSS FIGHT', summary: 'Boss spawn sequence, attack cycle timer.' },
      { name: 'BOSS ATTACK PATTERNS', summary: 'Phase-based attacks. Phase milestones.' },
      { name: 'RPG QUEST ENGINE', summary: 'Quest acceptance, journal, completion.' },
      { name: 'ECONOMY SYSTEM', summary: 'Currency, vendors, balance scoreboard.' },
      { name: 'LOOT TABLE SYSTEM', summary: 'Weighted loot rolls per rarity tier.' },
      { name: 'CINEMATIC SEQUENCES', summary: 'Camera positions, freeze + cutscene function.' },
      { name: 'PARKOUR COURSE', summary: 'Per-player timer, checkpoints, leaderboard.' },
      { name: 'CLASS SELECTION', summary: 'Class kits with stat modifiers.' },
      { name: 'WAVE SURVIVAL', summary: 'Endless waves with class scaling.' },
    ],
  },
};
